database:
  mysql:
    host: "localhost"
    port: "3306"
    username: "root"
    password: "password"
    database_name: "local"
    driver_name: "mysql"
    protocol: "tcp"
    timeout: "5s"

swagger:
  title: "Learning API Docs"
  description: "Learning is application to learning golang."
  version: "v1"
  host: "localhost:8080"
  base_path: "/api"
  schemes: ['http']

http_server:
  read_timeout: 10s
  write_timeout: 10s
  read_header_timeout: 10s